language: php

php:
  - 7.4
  -
before_script:
  - composer install --dev --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - vendor/bin/php-coveralls --coverage_clover=clover.xml -v