language: php

php:
  - 7.3

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - vendor/bin/php-coveralls --coverage_clover=clover.xml -v